version: '3'
services:

  geth:
    image: ethereum/client-go:latest
    restart: always
    command: >
      --ws
      --authrpc.port 8551
      --authrpc.addr=geth
      --authrpc.jwtsecret=/root/jwt/jwt.hex
      --authrpc.vhosts='*'
      --goerli 
      --http
      --http.port 8545
      --http.addr=geth
      --http.api eth,net,engine,admin,web3,debug
      --http.vhosts=*
      --metrics
      --metrics.addr=0.0.0.0
    ports: 
      - '8545:8545'
      - '8546:8546'
      - '8550:8550'
      - '8551:8551'
      - '6060:6060'
    volumes:
      - ./data/geth:/root/.ethereum
      - ./jwt.hex:/root/jwt/jwt.hex
  prysma:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    restart: always
    depends_on:
       - geth
    command: >
      --jwt-secret=/root/jwt/jwt.hex
      --execution-endpoint=http://geth:8551
      --prater
      --accept-terms-of-use
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --genesis-state=/genesis/genesis.ssz
      --checkpoint-block=/genesis/block_prater_capella_5257984-0xeb158779e14dd958a381fa6a798b0883b6936163a788103387bec8c20edb9506.ssz
      --checkpoint-state=/genesis/state_prater_capella_5257984-0x89a05deee425199ad1b8e6a98aa291ff1080e319abe83eec9e7b57fa73846e78.ssz
      --monitoring-host=prysma
      --suggested-fee-recipient=0x01234567722E6b0000012BFEBf6177F1D2e9758D9
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'
      - '8080:8080'
      - '12000:12000/udp'
    volumes:
      - ./data/prysma:/root/.eth2
      - ./jwt.hex:/root/jwt/jwt.hex
      - ./init:/genesis
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - '9090:9090'
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus:/etc/prometheus

  aggregator:
    image: aggregator
    build:
      dockerfile: Dockerfile
      context: ./aggregator
    restart: always
    ports:
      - "8085:8085"
